language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # SDL
  - sudo apt-get install libsdl1.2-dev

services:
  - xvfb

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_sdl &
  - sleep 10
